name:               "Nabil's Narrative"
description:        "Some of my Programming Projects"

url:                ""
author:             "Nabil Ahlhauser"
email:              "Nabil.Ahlhauser@my.maryvillecollege.edu"
gravatar_hash:      "a70796a247d24b369607ceabf5ce0baa"
github:             "SilverIronMan"
linkedin:           "nabil-ahlhauser"
facebook:           "silver9244"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
