# Site Settings
title: Nabil's Narrative
email: nabila9@gmail.com
description: I am a web developer
baseurl: "/nabilsnarrative" # the subpath of your site, e.g. /blog
url: "https://www.rossener.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Nabil Ahlhauser
user_description: I am a web developer.

img: "/nabilsnarrative/assets/img"

# Social Media
# Remove the item if you don't need it
github_username: SilverIronMan
facebook_username: silver9244
linkedin_username: nabil-ahlhauser

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
